//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("modelModel1", "FK__bookingde__equip__15502E78", "sportfacility", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sports_Facility.sportfacility), "bookingdetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sports_Facility.bookingdetail), true)]
[assembly: EdmRelationshipAttribute("modelModel1", "FK__bookingde__membe__145C0A3F", "members", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sports_Facility.member), "bookingdetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sports_Facility.bookingdetail), true)]

#endregion

namespace Sports_Facility
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class modelEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new modelEntities2 object using the connection string found in the 'modelEntities2' section of the application configuration file.
        /// </summary>
        public modelEntities2() : base("name=modelEntities2", "modelEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new modelEntities2 object.
        /// </summary>
        public modelEntities2(string connectionString) : base(connectionString, "modelEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new modelEntities2 object.
        /// </summary>
        public modelEntities2(EntityConnection connection) : base(connection, "modelEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bookingdetail> bookingdetails
        {
            get
            {
                if ((_bookingdetails == null))
                {
                    _bookingdetails = base.CreateObjectSet<bookingdetail>("bookingdetails");
                }
                return _bookingdetails;
            }
        }
        private ObjectSet<bookingdetail> _bookingdetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<member> members
        {
            get
            {
                if ((_members == null))
                {
                    _members = base.CreateObjectSet<member>("members");
                }
                return _members;
            }
        }
        private ObjectSet<member> _members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sportfacility> sportfacilities
        {
            get
            {
                if ((_sportfacilities == null))
                {
                    _sportfacilities = base.CreateObjectSet<sportfacility>("sportfacilities");
                }
                return _sportfacilities;
            }
        }
        private ObjectSet<sportfacility> _sportfacilities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bookingdetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobookingdetails(bookingdetail bookingdetail)
        {
            base.AddObject("bookingdetails", bookingdetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomembers(member member)
        {
            base.AddObject("members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sportfacilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosportfacilities(sportfacility sportfacility)
        {
            base.AddObject("sportfacilities", sportfacility);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="modelModel1", Name="bookingdetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bookingdetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bookingdetail object.
        /// </summary>
        /// <param name="bookingid">Initial value of the bookingid property.</param>
        /// <param name="memberid">Initial value of the memberid property.</param>
        /// <param name="equipmentid">Initial value of the equipmentid property.</param>
        /// <param name="dateofbooking">Initial value of the dateofbooking property.</param>
        /// <param name="c8_9_am">Initial value of the C8_9_am property.</param>
        /// <param name="c9_10_am">Initial value of the C9_10_am property.</param>
        /// <param name="c10_11_am">Initial value of the C10_11_am property.</param>
        /// <param name="c11_12_noon">Initial value of the C11_12_noon property.</param>
        /// <param name="c2_3_pm">Initial value of the C2_3_pm property.</param>
        /// <param name="c3_4_pm">Initial value of the C3_4_pm property.</param>
        /// <param name="c_4_5_pm">Initial value of the C_4_5_pm property.</param>
        /// <param name="c5_6_pm">Initial value of the C5_6_pm property.</param>
        /// <param name="c6_7_pm">Initial value of the C6_7_pm property.</param>
        /// <param name="c7_8_pm">Initial value of the C7_8_pm property.</param>
        public static bookingdetail Createbookingdetail(global::System.Int32 bookingid, global::System.Int32 memberid, global::System.Int32 equipmentid, global::System.DateTime dateofbooking, global::System.Int16 c8_9_am, global::System.Int16 c9_10_am, global::System.Int16 c10_11_am, global::System.Int16 c11_12_noon, global::System.Int16 c2_3_pm, global::System.Int16 c3_4_pm, global::System.Int16 c_4_5_pm, global::System.Int16 c5_6_pm, global::System.Int16 c6_7_pm, global::System.Int16 c7_8_pm)
        {
            bookingdetail bookingdetail = new bookingdetail();
            bookingdetail.bookingid = bookingid;
            bookingdetail.memberid = memberid;
            bookingdetail.equipmentid = equipmentid;
            bookingdetail.dateofbooking = dateofbooking;
            bookingdetail.C8_9_am = c8_9_am;
            bookingdetail.C9_10_am = c9_10_am;
            bookingdetail.C10_11_am = c10_11_am;
            bookingdetail.C11_12_noon = c11_12_noon;
            bookingdetail.C2_3_pm = c2_3_pm;
            bookingdetail.C3_4_pm = c3_4_pm;
            bookingdetail.C_4_5_pm = c_4_5_pm;
            bookingdetail.C5_6_pm = c5_6_pm;
            bookingdetail.C6_7_pm = c6_7_pm;
            bookingdetail.C7_8_pm = c7_8_pm;
            return bookingdetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bookingid
        {
            get
            {
                return _bookingid;
            }
            set
            {
                if (_bookingid != value)
                {
                    OnbookingidChanging(value);
                    ReportPropertyChanging("bookingid");
                    _bookingid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bookingid");
                    OnbookingidChanged();
                }
            }
        }
        private global::System.Int32 _bookingid;
        partial void OnbookingidChanging(global::System.Int32 value);
        partial void OnbookingidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 memberid
        {
            get
            {
                return _memberid;
            }
            set
            {
                OnmemberidChanging(value);
                ReportPropertyChanging("memberid");
                _memberid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("memberid");
                OnmemberidChanged();
            }
        }
        private global::System.Int32 _memberid;
        partial void OnmemberidChanging(global::System.Int32 value);
        partial void OnmemberidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 equipmentid
        {
            get
            {
                return _equipmentid;
            }
            set
            {
                OnequipmentidChanging(value);
                ReportPropertyChanging("equipmentid");
                _equipmentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("equipmentid");
                OnequipmentidChanged();
            }
        }
        private global::System.Int32 _equipmentid;
        partial void OnequipmentidChanging(global::System.Int32 value);
        partial void OnequipmentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateofbooking
        {
            get
            {
                return _dateofbooking;
            }
            set
            {
                OndateofbookingChanging(value);
                ReportPropertyChanging("dateofbooking");
                _dateofbooking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateofbooking");
                OndateofbookingChanged();
            }
        }
        private global::System.DateTime _dateofbooking;
        partial void OndateofbookingChanging(global::System.DateTime value);
        partial void OndateofbookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C8_9_am
        {
            get
            {
                return _C8_9_am;
            }
            set
            {
                OnC8_9_amChanging(value);
                ReportPropertyChanging("C8_9_am");
                _C8_9_am = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C8_9_am");
                OnC8_9_amChanged();
            }
        }
        private global::System.Int16 _C8_9_am;
        partial void OnC8_9_amChanging(global::System.Int16 value);
        partial void OnC8_9_amChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C9_10_am
        {
            get
            {
                return _C9_10_am;
            }
            set
            {
                OnC9_10_amChanging(value);
                ReportPropertyChanging("C9_10_am");
                _C9_10_am = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C9_10_am");
                OnC9_10_amChanged();
            }
        }
        private global::System.Int16 _C9_10_am;
        partial void OnC9_10_amChanging(global::System.Int16 value);
        partial void OnC9_10_amChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C10_11_am
        {
            get
            {
                return _C10_11_am;
            }
            set
            {
                OnC10_11_amChanging(value);
                ReportPropertyChanging("C10_11_am");
                _C10_11_am = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C10_11_am");
                OnC10_11_amChanged();
            }
        }
        private global::System.Int16 _C10_11_am;
        partial void OnC10_11_amChanging(global::System.Int16 value);
        partial void OnC10_11_amChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C11_12_noon
        {
            get
            {
                return _C11_12_noon;
            }
            set
            {
                OnC11_12_noonChanging(value);
                ReportPropertyChanging("C11_12_noon");
                _C11_12_noon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C11_12_noon");
                OnC11_12_noonChanged();
            }
        }
        private global::System.Int16 _C11_12_noon;
        partial void OnC11_12_noonChanging(global::System.Int16 value);
        partial void OnC11_12_noonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C2_3_pm
        {
            get
            {
                return _C2_3_pm;
            }
            set
            {
                OnC2_3_pmChanging(value);
                ReportPropertyChanging("C2_3_pm");
                _C2_3_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2_3_pm");
                OnC2_3_pmChanged();
            }
        }
        private global::System.Int16 _C2_3_pm;
        partial void OnC2_3_pmChanging(global::System.Int16 value);
        partial void OnC2_3_pmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C3_4_pm
        {
            get
            {
                return _C3_4_pm;
            }
            set
            {
                OnC3_4_pmChanging(value);
                ReportPropertyChanging("C3_4_pm");
                _C3_4_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C3_4_pm");
                OnC3_4_pmChanged();
            }
        }
        private global::System.Int16 _C3_4_pm;
        partial void OnC3_4_pmChanging(global::System.Int16 value);
        partial void OnC3_4_pmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C_4_5_pm
        {
            get
            {
                return _C_4_5_pm;
            }
            set
            {
                OnC_4_5_pmChanging(value);
                ReportPropertyChanging("C_4_5_pm");
                _C_4_5_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_4_5_pm");
                OnC_4_5_pmChanged();
            }
        }
        private global::System.Int16 _C_4_5_pm;
        partial void OnC_4_5_pmChanging(global::System.Int16 value);
        partial void OnC_4_5_pmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C5_6_pm
        {
            get
            {
                return _C5_6_pm;
            }
            set
            {
                OnC5_6_pmChanging(value);
                ReportPropertyChanging("C5_6_pm");
                _C5_6_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C5_6_pm");
                OnC5_6_pmChanged();
            }
        }
        private global::System.Int16 _C5_6_pm;
        partial void OnC5_6_pmChanging(global::System.Int16 value);
        partial void OnC5_6_pmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C6_7_pm
        {
            get
            {
                return _C6_7_pm;
            }
            set
            {
                OnC6_7_pmChanging(value);
                ReportPropertyChanging("C6_7_pm");
                _C6_7_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C6_7_pm");
                OnC6_7_pmChanged();
            }
        }
        private global::System.Int16 _C6_7_pm;
        partial void OnC6_7_pmChanging(global::System.Int16 value);
        partial void OnC6_7_pmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 C7_8_pm
        {
            get
            {
                return _C7_8_pm;
            }
            set
            {
                OnC7_8_pmChanging(value);
                ReportPropertyChanging("C7_8_pm");
                _C7_8_pm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C7_8_pm");
                OnC7_8_pmChanged();
            }
        }
        private global::System.Int16 _C7_8_pm;
        partial void OnC7_8_pmChanging(global::System.Int16 value);
        partial void OnC7_8_pmChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("modelModel1", "FK__bookingde__equip__15502E78", "sportfacility")]
        public sportfacility sportfacility
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sportfacility>("modelModel1.FK__bookingde__equip__15502E78", "sportfacility").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sportfacility>("modelModel1.FK__bookingde__equip__15502E78", "sportfacility").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sportfacility> sportfacilityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sportfacility>("modelModel1.FK__bookingde__equip__15502E78", "sportfacility");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sportfacility>("modelModel1.FK__bookingde__equip__15502E78", "sportfacility", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("modelModel1", "FK__bookingde__membe__145C0A3F", "members")]
        public member member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("modelModel1.FK__bookingde__membe__145C0A3F", "members").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("modelModel1.FK__bookingde__membe__145C0A3F", "members").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<member> memberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<member>("modelModel1.FK__bookingde__membe__145C0A3F", "members");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<member>("modelModel1.FK__bookingde__membe__145C0A3F", "members", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="modelModel1", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new member object.
        /// </summary>
        /// <param name="memberid">Initial value of the memberid property.</param>
        /// <param name="membername">Initial value of the membername property.</param>
        /// <param name="membericno">Initial value of the membericno property.</param>
        /// <param name="address">Initial value of the address property.</param>
        public static member Createmember(global::System.Int32 memberid, global::System.String membername, global::System.String membericno, global::System.String address)
        {
            member member = new member();
            member.memberid = memberid;
            member.membername = membername;
            member.membericno = membericno;
            member.address = address;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 memberid
        {
            get
            {
                return _memberid;
            }
            set
            {
                if (_memberid != value)
                {
                    OnmemberidChanging(value);
                    ReportPropertyChanging("memberid");
                    _memberid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("memberid");
                    OnmemberidChanged();
                }
            }
        }
        private global::System.Int32 _memberid;
        partial void OnmemberidChanging(global::System.Int32 value);
        partial void OnmemberidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String membername
        {
            get
            {
                return _membername;
            }
            set
            {
                OnmembernameChanging(value);
                ReportPropertyChanging("membername");
                _membername = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("membername");
                OnmembernameChanged();
            }
        }
        private global::System.String _membername;
        partial void OnmembernameChanging(global::System.String value);
        partial void OnmembernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String membericno
        {
            get
            {
                return _membericno;
            }
            set
            {
                OnmembericnoChanging(value);
                ReportPropertyChanging("membericno");
                _membericno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("membericno");
                OnmembericnoChanged();
            }
        }
        private global::System.String _membericno;
        partial void OnmembericnoChanging(global::System.String value);
        partial void OnmembericnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phonenumber
        {
            get
            {
                return _phonenumber;
            }
            set
            {
                OnphonenumberChanging(value);
                ReportPropertyChanging("phonenumber");
                _phonenumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phonenumber");
                OnphonenumberChanged();
            }
        }
        private global::System.String _phonenumber;
        partial void OnphonenumberChanging(global::System.String value);
        partial void OnphonenumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Emailid
        {
            get
            {
                return _Emailid;
            }
            set
            {
                OnEmailidChanging(value);
                ReportPropertyChanging("Emailid");
                _Emailid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Emailid");
                OnEmailidChanged();
            }
        }
        private global::System.String _Emailid;
        partial void OnEmailidChanging(global::System.String value);
        partial void OnEmailidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("modelModel1", "FK__bookingde__membe__145C0A3F", "bookingdetails")]
        public EntityCollection<bookingdetail> bookingdetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<bookingdetail>("modelModel1.FK__bookingde__membe__145C0A3F", "bookingdetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<bookingdetail>("modelModel1.FK__bookingde__membe__145C0A3F", "bookingdetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="modelModel1", Name="sportfacility")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sportfacility : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sportfacility object.
        /// </summary>
        /// <param name="equipmentname">Initial value of the equipmentname property.</param>
        /// <param name="equipmentid">Initial value of the equipmentid property.</param>
        /// <param name="facilityavailable">Initial value of the facilityavailable property.</param>
        public static sportfacility Createsportfacility(global::System.String equipmentname, global::System.Int32 equipmentid, global::System.Int16 facilityavailable)
        {
            sportfacility sportfacility = new sportfacility();
            sportfacility.equipmentname = equipmentname;
            sportfacility.equipmentid = equipmentid;
            sportfacility.facilityavailable = facilityavailable;
            return sportfacility;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String equipmentname
        {
            get
            {
                return _equipmentname;
            }
            set
            {
                OnequipmentnameChanging(value);
                ReportPropertyChanging("equipmentname");
                _equipmentname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("equipmentname");
                OnequipmentnameChanged();
            }
        }
        private global::System.String _equipmentname;
        partial void OnequipmentnameChanging(global::System.String value);
        partial void OnequipmentnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 equipmentid
        {
            get
            {
                return _equipmentid;
            }
            set
            {
                if (_equipmentid != value)
                {
                    OnequipmentidChanging(value);
                    ReportPropertyChanging("equipmentid");
                    _equipmentid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("equipmentid");
                    OnequipmentidChanged();
                }
            }
        }
        private global::System.Int32 _equipmentid;
        partial void OnequipmentidChanging(global::System.Int32 value);
        partial void OnequipmentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 facilityavailable
        {
            get
            {
                return _facilityavailable;
            }
            set
            {
                OnfacilityavailableChanging(value);
                ReportPropertyChanging("facilityavailable");
                _facilityavailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("facilityavailable");
                OnfacilityavailableChanged();
            }
        }
        private global::System.Int16 _facilityavailable;
        partial void OnfacilityavailableChanging(global::System.Int16 value);
        partial void OnfacilityavailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("modelModel1", "FK__bookingde__equip__15502E78", "bookingdetails")]
        public EntityCollection<bookingdetail> bookingdetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<bookingdetail>("modelModel1.FK__bookingde__equip__15502E78", "bookingdetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<bookingdetail>("modelModel1.FK__bookingde__equip__15502E78", "bookingdetails", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
